package com.aimv.domain.chain;

public enum ChainRunStatus {
    CREATED,
    CONTEXT_LOADING,
    RAG_RETRIEVING,
    PREVIOUS_REVIEWING,
    CAPABILITY_PLANNING,
    EXECUTING,
    QUALITY_REVIEWING,
    HANDOFF_WRITING,
    KNOWLEDGE_INGESTING,
    SUCCEEDED,
    WAITING_USER,
    WAITING_CAPABILITY,
    WAITING_REVIEW,
    FAILED,
    CANCELLED
}
